$env:ORACLE_USER="rawdata"
$env:ORACLE_PASSWORD="rawdata"
$env:ORACLE_DSN="192.168.96.97:1521/OASIPDB"

$env:OGG_REST_BASE_URL="http://192.168.96.119:9010"
$env:OGG_REST_DEPLOYMENT_NAME="GG-01"
$env:OGG_REST_CONNECTION="OracleGoldenGate"
$env:OGG_REST_MODE="OGG_REST_SKELETON"
$env:TRANDATA_SCOPE="TABLE"

$env:PREPARE_SOURCE_EXECUTOR="OGG_REST_SKELETON"
$env:ATTACH_EXTRACT_EXECUTOR="OGG_REST_SKELETON"
$env:ATTACH_REPLICAT_EXECUTOR="OGG_REST_SKELETON"

$env:PREPARE_SOURCE_MODE="DRY_RUN"
$env:ATTACH_EXTRACT_MODE="DRY_RUN"
$env:INITIAL_LOAD_EXECUTOR="DRY_RUN"
$env:INITIAL_LOAD_MODE="DRY_RUN"
$env:INSTANTIATION_EXECUTOR="DRY_RUN"
$env:INSTANTIATION_MODE="DRY_RUN"
$env:ATTACH_REPLICAT_MODE="DRY_RUN"
$env:ACTIVATION_EXECUTOR="DRY_RUN"
$env:ACTIVATION_MODE="DRY_RUN"

$env:INITIAL_LOAD_EXECUTOR="SCRIPT"
$env:INITIAL_LOAD_SCRIPT_COMMAND='python scripts/mock_initial_load_runner.py {request} {response}'
$env:INITIAL_LOAD_SCRIPT_TIMEOUT_SEC="3600"

python main.py