$ErrorActionPreference = "Stop"

$env:PYTHONPATH = "."

$env:ORACLE_USER = "rawdata"
$env:ORACLE_PASSWORD = "rawdata"
$env:ORACLE_DSN = "192.168.96.97:1521/OASIPDB"

$env:ENVIRONMENT_NAME = "dev"
$env:DESIRED_STATE_PATH = "registry/desired_state.json"

$env:PREPARE_SOURCE_ACTION = "APPLY"
$env:PREPARE_SOURCE_EXECUTOR = "DRY_RUN"

$env:ATTACH_EXTRACT_ACTION = "APPLY"
$env:ATTACH_EXTRACT_EXECUTOR = "SCRIPT"
$env:ATTACH_EXTRACT_SCRIPT_COMMAND = "python scripts/attach_extract_adapter.py {request} {response}"
$env:ATTACH_EXTRACT_SCRIPT_TIMEOUT_SEC = "1800"

$env:INITIAL_LOAD_ACTION = "APPLY"
$env:INITIAL_LOAD_EXECUTOR = "SCRIPT"
$env:INITIAL_LOAD_SCRIPT_COMMAND = "python scripts/initial_load_adapter.py {request} {response}"
$env:INITIAL_LOAD_SCRIPT_TIMEOUT_SEC = "3600"

$env:INSTANTIATION_ACTION = "APPLY"
$env:INSTANTIATION_EXECUTOR = "DRY_RUN"

$env:ATTACH_REPLICAT_ACTION = "APPLY"
$env:ATTACH_REPLICAT_EXECUTOR = "SCRIPT"
$env:ATTACH_REPLICAT_SCRIPT_COMMAND = "python scripts/attach_replicat_adapter.py {request} {response}"
$env:ATTACH_REPLICAT_SCRIPT_TIMEOUT_SEC = "1800"

$env:ACTIVATION_ACTION = "APPLY"
$env:ACTIVATION_EXECUTOR = "DRY_RUN"

$env:OGG_REST_BASE_URL = "http://192.168.96.119:9010"
$env:OGG_REST_USERNAME = "ggadmin"
$env:OGG_REST_PASSWORD = "1q2w3e!Q@W#E"
$env:OGG_REST_DEPLOYMENT_NAME = "GG-01"
$env:OGG_REST_VERIFY_SSL = "false"
$env:OGG_REST_MODE = "OGG_REST_REAL"
$env:OGG_REST_CONNECTION = "OracleGoldenGate"
$env:TRANDATA_SCOPE = "TABLE"
$env:ALLOW_REAL_PREPARE_SOURCE = "false"

$env:SOURCE_DB_CONNECT_STRING = "source_user/source_user@//192.168.96.100:1521/SRCPDB"
$env:TARGET_DB_CONNECT_STRING = "rawdata/rawdata@//192.168.96.97:1521/OASIPDB"
$env:DATAPUMP_NETWORK_LINK = "source_link"
$env:DATAPUMP_DIRECTORY = "DATA_PUMP_DIR"
$env:INITIAL_LOAD_REQUIRE_EMPTY_TARGET = "true"
$env:DATAPUMP_DEFAULT_PARALLEL = "1"

$env:OGG_ADMIN_URL = "http://192.168.96.119:9010"
$env:OGG_ADMIN_DEPLOYMENT = "GG-01"
$env:OGG_ADMIN_USER = "ggadmin"
$env:OGG_ADMIN_PASSWORD = "1q2w3e!Q@W#E"
$env:OGG_ADMINCLIENT_PATH = "adminclient"
$env:OGG_PARAM_DIR = "/u01/app/OGG21MA/DEPLOYMENTS/GG-01/etc/conf/ogg"

Write-Host "PREPARE_SOURCE_ACTION=$env:PREPARE_SOURCE_ACTION"
Write-Host "PREPARE_SOURCE_EXECUTOR=$env:PREPARE_SOURCE_EXECUTOR"
Write-Host "ATTACH_EXTRACT_ACTION=$env:ATTACH_EXTRACT_ACTION"
Write-Host "ATTACH_EXTRACT_EXECUTOR=$env:ATTACH_EXTRACT_EXECUTOR"
Write-Host "INITIAL_LOAD_ACTION=$env:INITIAL_LOAD_ACTION"
Write-Host "INITIAL_LOAD_EXECUTOR=$env:INITIAL_LOAD_EXECUTOR"
Write-Host "ATTACH_REPLICAT_ACTION=$env:ATTACH_REPLICAT_ACTION"
Write-Host "ATTACH_REPLICAT_EXECUTOR=$env:ATTACH_REPLICAT_EXECUTOR"

python main.py