$ErrorActionPreference = "Stop"

$env:PYTHONPATH = "."
$env:ORACLE_USER = "rawdata"
$env:ORACLE_PASSWORD = "rawdata"
$env:ORACLE_DSN = "192.168.96.97:1521/OASIPDB"

$env:ENVIRONMENT_NAME = "dev"
$env:DESIRED_STATE_PATH = "registry/desired_state.json"

$env:PREPARE_SOURCE_ACTION = "SKIP"
$env:ATTACH_EXTRACT_ACTION = "SKIP"
$env:INITIAL_LOAD_ACTION = "SKIP"
$env:INSTANTIATION_ACTION = "SKIP"
$env:ATTACH_REPLICAT_ACTION = "SKIP"
$env:ACTIVATION_ACTION = "SKIP"

$env:PREPARE_SOURCE_EXECUTOR = "DRY_RUN"
$env:ATTACH_EXTRACT_EXECUTOR = "SCRIPT"
$env:INITIAL_LOAD_EXECUTOR = "SCRIPT"
$env:INSTANTIATION_EXECUTOR = "DRY_RUN"
$env:ATTACH_REPLICAT_EXECUTOR = "SCRIPT"
$env:ACTIVATION_EXECUTOR = "DRY_RUN"

$env:OGG_REST_BASE_URL = "http://192.168.96.119:9010"
$env:OGG_REST_USERNAME = "ggadmin"
$env:OGG_REST_PASSWORD = "1q2w3e!Q@W#E"
$env:OGG_REST_DEPLOYMENT_NAME = "GG-01"
$env:OGG_REST_VERIFY_SSL = "false"
$env:OGG_REST_MODE = "OGG_REST_REAL"
$env:OGG_REST_CONNECTION = "OracleGoldenGate"
$env:TRANDATA_SCOPE = "TABLE"
$env:ALLOW_REAL_PREPARE_SOURCE = "false"

python main.py