from enum import Enum


class ReplicationMode(str, Enum):
    INITIAL_PLUS_CDC = "INITIAL_PLUS_CDC"
    CDC_ONLY = "CDC_ONLY"
    INITIAL_LOAD_ONLY = "INITIAL_LOAD_ONLY"


class LoadMethod(str, Enum):
    DATAPUMP = "DATAPUMP"
    OGG_INITIAL_LOAD = "OGG_INITIAL_LOAD"
    CUSTOM_SQL = "CUSTOM_SQL"


class TableState(str, Enum):
    NEW = "NEW"
    PLANNED = "PLANNED"
    PREPARED = "PREPARED"
    CDC_CAPTURE_ATTACHED = "CDC_CAPTURE_ATTACHED"
    INITIAL_LOAD_PENDING = "INITIAL_LOAD_PENDING"
    INITIAL_LOAD_RUNNING = "INITIAL_LOAD_RUNNING"
    INITIAL_LOAD_DONE = "INITIAL_LOAD_DONE"
    INSTANTIATED = "INSTANTIATED"
    CDC_APPLY_ATTACHED = "CDC_APPLY_ATTACHED"
    ACTIVE = "ACTIVE"
    ERROR = "ERROR"
    REMOVAL_PLANNED = "REMOVAL_PLANNED"
    REMOVED = "REMOVED"


class ValidationStatus(str, Enum):
    UNKNOWN = "UNKNOWN"
    PENDING = "PENDING"
    PASSED = "PASSED"
    FAILED = "FAILED"


class EventStatus(str, Enum):
    STARTED = "STARTED"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


class EventType(str, Enum):
    TABLE_DISCOVERED = "TABLE_DISCOVERED"
    TABLE_REGISTERED = "TABLE_REGISTERED"
    TABLE_PLANNED = "TABLE_PLANNED"
    SOURCE_PREPARE_STARTED = "SOURCE_PREPARE_STARTED"
    SOURCE_PREPARE_DONE = "SOURCE_PREPARE_DONE"
    CDC_CAPTURE_ATTACH_STARTED = "CDC_CAPTURE_ATTACH_STARTED"
    CDC_CAPTURE_ATTACH_DONE = "CDC_CAPTURE_ATTACH_DONE"
    INITIAL_LOAD_STARTED = "INITIAL_LOAD_STARTED"
    INITIAL_LOAD_DONE = "INITIAL_LOAD_DONE"
    INSTANTIATION_RECORDED = "INSTANTIATION_RECORDED"
    CDC_APPLY_ATTACH_STARTED = "CDC_APPLY_ATTACH_STARTED"
    CDC_APPLY_ATTACH_DONE = "CDC_APPLY_ATTACH_DONE"
    VALIDATION_STARTED = "VALIDATION_STARTED"
    VALIDATION_PASSED = "VALIDATION_PASSED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    TABLE_ACTIVATED = "TABLE_ACTIVATED"
    TABLE_REMOVAL_PLANNED = "TABLE_REMOVAL_PLANNED"
    TABLE_REMOVED = "TABLE_REMOVED"
    ROLLBACK_STARTED = "ROLLBACK_STARTED"
    ROLLBACK_DONE = "ROLLBACK_DONE"
    ERROR_OCCURRED = "ERROR_OCCURRED"
